package:
  name: proc-tree
  version: 0.1.0

source:
  path: ..

build:
  number: 0
  # script: call bld.bat # [win]
  # script: call build.sh # [linux]


requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }} # [linux]
    # - m2w64-gcc-toolchain # [win]

  host:
    - libstdcxx-ng # [linux]

  run:
    - libstdcxx-ng # [linux]

about:
  summary: A C++ library that prints for process tree.
  license: MIT