name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3.3.0
        with:
          miniforge-variant: Miniforge3
          auto-activate: true
          conda-remove-defaults: true
          channels: conda-forge

      - name: Install Build Tools
        shell: bash -el {0}
        run: |
            mamba install -y conda-build anaconda-client

      - name: Build Conda Package
        shell: bash -el {0}
        run: |
            conda build conda-recipe --output-folder dist

      - name: Upload Package
        uses: actions/upload-artifact@v7.0.1
        with:
          name: proc-tree-package
          path: |
            dist/**/*.conda
            dist/**/*.tar.bz2
          if-no-files-found: error


